version: "1.0"
services:
  app:
    build: .
    image: react-demo:build # <-- tÃªn image build-only
    container_name: react-demo-build
    networks:
      - app-network
    restart: never
networks:
  app-network:
    driver: bridge
